# =============================================================================
# app.py — Vault Observer: Operator Audit Dashboard
# =============================================================================
# A Streamlit application that reads Vault's file audit log and calls the
# Vault API to display a human-readable trace of every authentication event.
#
# Pages:
#   1. Auth Events          — JWT logins, policies applied, entity IDs
#   2. Credential Issuance  — Dynamic DB credentials issued per user
#   3. Entity Explorer      — Current Vault entities and their group memberships
#   4. Token Lifecycle      — Token create/renew/revoke events
#   5. SIEM Context         — What Vault logs provide vs what a SIEM adds
#
# This container is for operator/SE use during the demo. It connects to Vault
# using the root token (read-only queries) and reads the audit log file mounted
# from ~/.demo/vault/logs/audit.log on the host.
# =============================================================================

import json
import os
import pathlib
import requests
import streamlit as st
import pandas as pd
from datetime import datetime, timezone
from dotenv import load_dotenv

# Load environment variables from /app/.env (mounted by docker-compose)
load_dotenv("/app/.env")

# ── Configuration ─────────────────────────────────────────────────────────────
# These are injected via the .env file generated by Ansible.
# VAULT_ADDR points to the vault-enterprise container by service name.
# VAULT_TOKEN is the root token — used only for read-only API queries here.
VAULT_ADDR      = os.getenv("VAULT_ADDR", "http://vault-enterprise:8200")
VAULT_TOKEN     = os.getenv("VAULT_TOKEN", "")
VAULT_NAMESPACE = os.getenv("VAULT_NAMESPACE", "")

# Path to Vault's audit log file inside this container.
# The host directory ~/.demo/vault/logs is mounted at /vault/logs (read-only).
LOG_PATH = pathlib.Path("/vault/logs/audit.log")

# ── Streamlit page config ─────────────────────────────────────────────────────
st.set_page_config(
    page_title="Vault Observer — Operator Dashboard",
    page_icon="🔐",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Sidebar navigation ────────────────────────────────────────────────────────
st.sidebar.title("🔐 Vault Observer")
st.sidebar.caption("Operator Audit Dashboard")
st.sidebar.markdown("---")
page = st.sidebar.radio(
    "Navigate",
    [
        "Auth Events",
        "Credential Issuance",
        "Entity Explorer",
        "Token Lifecycle",
        "SIEM Context",
    ],
)
st.sidebar.markdown("---")
st.sidebar.markdown(
    "**Vault UI:** [localhost:8200](http://localhost:8200/ui)  \n"
    "**Demo App:** [localhost:8501](http://localhost:8501)"
)

# Auto-refresh toggle — useful for live demo (re-reads audit log on each run)
auto_refresh = st.sidebar.checkbox("Auto-refresh (5s)", value=False)
if auto_refresh:
    import time
    time.sleep(5)
    st.rerun()


# =============================================================================
# Helper functions
# =============================================================================

def load_audit_events():
    """
    Read and parse the Vault audit log file.

    Vault writes one JSON object per line (newline-delimited JSON / NDJSON).
    Each line is a complete audit record — either a 'request' or 'response' type.
    Returns a list of parsed dicts, oldest first.
    """
    if not LOG_PATH.exists():
        return []
    events = []
    for line in LOG_PATH.read_text(errors="replace").splitlines():
        line = line.strip()
        if line:
            try:
                events.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    return events


def filter_responses(events):
    """Return only response-type events (these carry auth + policy data)."""
    return [e for e in events if e.get("type") == "response"]


def filter_auth_logins(events):
    """
    Return response events for JWT auth logins.
    These are the events that show WHO logged in, WHAT policy Vault applied,
    and WHICH entity was created/linked.
    """
    return [
        e for e in filter_responses(events)
        if "auth/jwt/login" in e.get("request", {}).get("path", "")
        and e.get("auth") is not None
    ]


def filter_cred_events(events):
    """
    Return response events for dynamic database credential issuance.
    These are the events that show WHICH user got a DB credential and WHAT role.
    """
    return [
        e for e in filter_responses(events)
        if "database/creds/" in e.get("request", {}).get("path", "")
    ]


def filter_token_events(events):
    """Return response events related to token lifecycle operations."""
    return [
        e for e in filter_responses(events)
        if e.get("request", {}).get("path", "").startswith("auth/token/")
    ]


def fmt_time(iso_str):
    """Format an ISO8601 timestamp to a readable local time string."""
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.astimezone().strftime("%Y-%m-%d %H:%M:%S")
    except Exception:
        return iso_str


def vault_get(path, root_level=False):
    """
    Make a GET request to the Vault API.

    Args:
        path:       The Vault API path (e.g., "identity/entity/id/<id>")
        root_level: If True, omit the X-Vault-Namespace header.

    Returns the parsed JSON response body, or None on error.
    """
    headers = {"X-Vault-Token": VAULT_TOKEN}
    if not root_level and VAULT_NAMESPACE:
        headers["X-Vault-Namespace"] = VAULT_NAMESPACE
    try:
        r = requests.get(f"{VAULT_ADDR}/v1/{path}", headers=headers, timeout=5)
        r.raise_for_status()
        return r.json()
    except requests.exceptions.ConnectionError:
        st.error(f"Cannot reach Vault at {VAULT_ADDR}. Is vault-enterprise running?")
        return None
    except requests.exceptions.HTTPError as e:
        st.error(f"Vault API error: {e}")
        return None


def vault_list(path, root_level=False):
    """
    Make a LIST request to the Vault API.

    Vault's list operation uses the HTTP LIST method (not GET ?list=true).
    This is required for identity/entity, identity/group, etc.

    Args:
        path:       The Vault API path (e.g., "identity/entity")
        root_level: If True, omit the X-Vault-Namespace header.

    Returns the parsed JSON response body, or None on error.
    """
    headers = {"X-Vault-Token": VAULT_TOKEN}
    if not root_level and VAULT_NAMESPACE:
        headers["X-Vault-Namespace"] = VAULT_NAMESPACE
    try:
        r = requests.request(
            "LIST", f"{VAULT_ADDR}/v1/{path}", headers=headers, timeout=5
        )
        if r.status_code == 404:
            # Vault returns 404 when there are no entries — treat as empty list
            return {"data": {"keys": []}}
        r.raise_for_status()
        return r.json()
    except requests.exceptions.ConnectionError:
        st.error(f"Cannot reach Vault at {VAULT_ADDR}. Is vault-enterprise running?")
        return None
    except requests.exceptions.HTTPError as e:
        st.error(f"Vault API error: {e}")
        return None


def build_entity_map(auth_events):
    """
    Build a lookup dict: entity_id → display_name
    from the auth login events. Used to correlate credential issuance events
    (which carry entity_id but not the user's name) back to the human user.
    """
    entity_map = {}
    for e in auth_events:
        auth = e.get("auth", {})
        eid = auth.get("entity_id", "")
        name = auth.get("display_name", "")
        if eid and name:
            entity_map[eid] = name
    return entity_map


# =============================================================================
# Page 1: Auth Events
# =============================================================================
if page == "Auth Events":
    st.title("🔑 Auth Events")
    st.markdown(
        "Every time a user authenticates via Vault's JWT auth backend, "
        "Vault records the full event — including which policies were applied "
        "and which Vault entity was linked. This is the **first link** in the "
        "identity chain: User → Entra ID JWT → Vault entity → Policy."
    )

    events = load_audit_events()
    auth_events = filter_auth_logins(events)

    if not auth_events:
        st.info(
            "No auth events found yet. Make sure:\n"
            "1. Vault audit logging is enabled (`terraform apply` was run).\n"
            "2. A user has signed in at http://localhost:8501."
        )
        if not LOG_PATH.exists():
            st.warning(f"Audit log file not found at `{LOG_PATH}`. "
                       "Vault may not have written any events yet.")
    else:
        st.success(f"Found **{len(auth_events)}** auth login event(s).")

        rows = []
        for e in reversed(auth_events):  # newest first
            auth = e.get("auth", {})
            policies = auth.get("policies", [])
            # Remove default policy from display — it's always present
            visible_policies = [p for p in policies if p != "default"]
            rows.append({
                "Time": fmt_time(e.get("time", "")),
                "User": auth.get("display_name", "—"),
                "Policies Applied": ", ".join(visible_policies) if visible_policies else "default only",
                "Token TTL (s)": auth.get("token_ttl", "—"),
                "Entity ID": auth.get("entity_id", "—")[:8] + "…",  # truncate for display
            })

        df = pd.DataFrame(rows)
        st.dataframe(df, use_container_width=True, hide_index=True)

        # Raw event expander for deep inspection
        with st.expander("🔍 Inspect raw event JSON"):
            selected = st.selectbox(
                "Select event to inspect",
                options=range(len(auth_events)),
                format_func=lambda i: (
                    f"{fmt_time(auth_events[-(i+1)].get('time',''))} — "
                    f"{auth_events[-(i+1)].get('auth',{}).get('display_name','unknown')}"
                ),
            )
            st.json(auth_events[-(selected + 1)])

    st.markdown("---")
    st.markdown(
        "**What this shows:** Vault sees the user's Entra ID JWT, validates it against "
        "the JWKS endpoint, extracts the `groups` claim, maps group Object IDs to Vault "
        "identity group aliases, and applies the corresponding policy — all in one step."
    )


# =============================================================================
# Page 2: Credential Issuance
# =============================================================================
elif page == "Credential Issuance":
    st.title("🗝️ Credential Issuance")
    st.markdown(
        "Every time the MCP server requests a short-lived MongoDB credential "
        "from Vault, an audit event is recorded. These events show **which user** "
        "got **which credential role** and how long it lasts."
    )

    events = load_audit_events()
    auth_events = filter_auth_logins(events)
    cred_events = filter_cred_events(events)
    entity_map = build_entity_map(auth_events)

    if not cred_events:
        st.info(
            "No credential issuance events found yet. "
            "Ask a question in the demo app (http://localhost:8501) to trigger one."
        )
    else:
        st.success(f"Found **{len(cred_events)}** credential issuance event(s).")

        rows = []
        for e in reversed(cred_events):  # newest first
            auth = e.get("auth", {})
            req  = e.get("request", {})
            resp = e.get("response", {})
            resp_data = resp.get("data", {}) or {}

            # Credential path tells us readonly vs readwrite
            cred_path = req.get("path", "—")
            role = cred_path.replace("database/creds/", "") if "database/creds/" in cred_path else cred_path

            # Correlate entity_id back to a human username from prior auth events
            entity_id = auth.get("entity_id", "")
            user = entity_map.get(entity_id, auth.get("display_name", "—"))

            rows.append({
                "Time": fmt_time(e.get("time", "")),
                "User": user,
                "Credential Role": role,
                "DB Username Issued": resp_data.get("username", "—"),
                "Lease Duration (s)": resp_data.get("lease_duration", "—"),
                "Renewable": resp_data.get("renewable", "—"),
            })

        df = pd.DataFrame(rows)
        st.dataframe(df, use_container_width=True, hide_index=True)

        with st.expander("🔍 Inspect raw event JSON"):
            selected = st.selectbox(
                "Select event",
                options=range(len(cred_events)),
                format_func=lambda i: (
                    f"{fmt_time(cred_events[-(i+1)].get('time',''))} — "
                    f"{cred_events[-(i+1)].get('request',{}).get('path','')}"
                ),
            )
            st.json(cred_events[-(selected + 1)])

    st.markdown("---")
    st.markdown(
        "**What this shows:** Each DB credential is unique, short-lived (5-minute TTL), "
        "and scoped to exactly what the user's policy allows. The credential is never "
        "stored anywhere — it exists only for the duration of the request."
    )


# =============================================================================
# Page 3: Entity Explorer
# =============================================================================
elif page == "Entity Explorer":
    st.title("🧑 Entity Explorer")
    st.markdown(
        "Vault creates an **entity** the first time a user authenticates. "
        "Entities persist across sessions and accumulate metadata — aliases, "
        "group memberships, and applied policies. This page calls the Vault "
        "Identity API directly to show current entity state."
    )

    if not VAULT_TOKEN:
        st.error("VAULT_TOKEN is not set. Check vault-observer/.env.")
        st.stop()

    # List all entity IDs in the namespace (requires HTTP LIST method)
    resp = vault_list("identity/entity")

    if resp is None:
        st.stop()

    entity_ids = resp.get("data", {}).get("keys", [])

    if not entity_ids:
        st.info(
            "No entities found yet. Sign in at http://localhost:8501 "
            "as Alice or Bob to create entities."
        )
    else:
        st.success(f"Found **{len(entity_ids)}** entity/entities in namespace `{VAULT_NAMESPACE}`.")

        for eid in entity_ids:
            entity = vault_get(f"identity/entity/id/{eid}")
            if entity is None:
                continue
            data = entity.get("data", {})
            name = data.get("name", eid)

            with st.expander(f"🧑 {name}", expanded=True):
                col1, col2 = st.columns(2)

                with col1:
                    st.markdown("**Entity ID**")
                    st.code(data.get("id", "—"))

                    st.markdown("**Policies (direct)**")
                    direct_policies = data.get("policies", [])
                    st.write(direct_policies if direct_policies else "None (inherited from groups)")

                    st.markdown("**Metadata**")
                    meta = data.get("metadata", {})
                    if meta:
                        for k, v in meta.items():
                            st.write(f"- `{k}`: {v}")
                    else:
                        st.write("None")

                with col2:
                    st.markdown("**Aliases (auth method links)**")
                    aliases = data.get("aliases", [])
                    for alias in aliases:
                        st.write(f"- `{alias.get('name', '—')}` via `{alias.get('mount_path', '—')}`")

                    st.markdown("**Group Memberships**")
                    groups = data.get("group_ids", [])
                    if groups:
                        for gid in groups:
                            g = vault_get(f"identity/group/id/{gid}")
                            if g:
                                gdata = g.get("data", {})
                                st.write(
                                    f"- **{gdata.get('name', gid)}** "
                                    f"→ policies: {gdata.get('policies', [])}"
                                )
                    else:
                        st.write("No direct group memberships found. "
                                 "External groups are resolved at login time from JWT claims.")

    st.markdown("---")
    st.markdown(
        "**What this shows:** Vault's Identity system is the bridge between the "
        "external identity provider (Entra ID) and internal authorization (policies). "
        "Once an entity exists, its group memberships are re-evaluated on every login "
        "from the JWT `groups` claim — no manual provisioning required."
    )


# =============================================================================
# Page 4: Token Lifecycle
# =============================================================================
elif page == "Token Lifecycle":
    st.title("⏱️ Token Lifecycle")
    st.markdown(
        "Vault issues a short-lived token to the MCP server after each successful "
        "JWT authentication. This page shows the full lifecycle of those tokens — "
        "creation, renewal, and revocation."
    )

    events = load_audit_events()
    auth_events = filter_auth_logins(events)
    token_events = filter_token_events(events)
    entity_map = build_entity_map(auth_events)

    # Also include the auth login events themselves as "Token Created" entries
    all_token_rows = []

    # Auth login responses → token created
    for e in auth_events:
        auth = e.get("auth", {})
        all_token_rows.append({
            "Time": fmt_time(e.get("time", "")),
            "Operation": "Token Created (JWT Login)",
            "User": auth.get("display_name", "—"),
            "TTL (s)": auth.get("token_ttl", "—"),
            "Policies": ", ".join(p for p in auth.get("policies", []) if p != "default"),
        })

    # Explicit token operations
    for e in token_events:
        auth = e.get("auth", {})
        req  = e.get("request", {})
        op   = req.get("path", "").replace("auth/token/", "").title()
        entity_id = auth.get("entity_id", "")
        user = entity_map.get(entity_id, auth.get("display_name", "—"))
        all_token_rows.append({
            "Time": fmt_time(e.get("time", "")),
            "Operation": op,
            "User": user,
            "TTL (s)": auth.get("token_ttl", "—"),
            "Policies": ", ".join(p for p in auth.get("policies", []) if p != "default"),
        })

    if not all_token_rows:
        st.info("No token events found yet. Sign in at http://localhost:8501 to generate tokens.")
    else:
        # Sort by time, newest first
        df = pd.DataFrame(all_token_rows).sort_values("Time", ascending=False)
        st.dataframe(df, use_container_width=True, hide_index=True)

    st.markdown("---")
    st.markdown(
        "**What this shows:** Every token is ephemeral. The MCP server's token expires "
        "after the TTL shown above — it cannot be reused. If the token leaks, it provides "
        "access only until expiry, and only to the paths permitted by the attached policy."
    )


# =============================================================================
# Page 5: SIEM Context
# =============================================================================
elif page == "SIEM Context":
    st.title("📊 Do You Need a SIEM?")
    st.markdown(
        "A common question: **Can operators trace everything from Vault logs alone, "
        "or do they need a SIEM to make sense of it?**"
    )

    st.markdown("---")

    # ── What Vault Provides ───────────────────────────────────────────────────
    st.subheader("✅ What Vault Audit Logs Provide — Without a SIEM")
    st.success(
        "For this demo, Vault audit logs are **fully sufficient** to trace every "
        "authentication and authorization event from login to database operation."
    )

    vault_capabilities = {
        "Question": [
            "Who logged in?",
            "What JWT claims did Vault see?",
            "What policy was applied?",
            "What DB credential was issued?",
            "What is the DB username?",
            "When does the credential expire?",
            "Did a write attempt fail?",
            "Full end-to-end identity trace?",
            "Which Entra ID group did the user belong to?",
        ],
        "Vault Audit Log Field": [
            "`auth.display_name` → e.g. `jwt-alice@contoso.com`",
            "`request.data` (login) → role, JWT claims",
            "`auth.policies` → e.g. `[\"readonly\"]`",
            "`request.path` → e.g. `database/creds/readonly`",
            "`response.data.username` → dynamically generated",
            "`response.lease_duration` → e.g. `300` seconds",
            "`response.data.errors` + HTTP status in response log",
            "`auth.entity_id` links all events to one Vault entity",
            "Derived: group alias `name` = Entra group Object ID in JWT `groups` claim",
        ],
    }
    st.dataframe(pd.DataFrame(vault_capabilities), use_container_width=True, hide_index=True)

    st.markdown("---")

    # ── What a SIEM Adds ──────────────────────────────────────────────────────
    st.subheader("⚠️ What a SIEM Adds — For Production")
    st.warning(
        "In production, a SIEM is recommended — not because Vault logs are incomplete, "
        "but because Vault is only one system. Threats often span multiple systems."
    )

    siem_capabilities = {
        "Capability": [
            "Cross-system correlation",
            "Long-term log retention",
            "Anomaly detection",
            "Real-time alerting",
            "Multi-cluster aggregation",
            "AI-generated summaries",
            "Compliance reporting",
            "Forensic timeline reconstruction",
        ],
        "Vault Alone": [
            "❌ Only Vault events",
            "⚠️ Limited by local disk / log rotation",
            "❌ No baselines, no ML",
            "❌ No alerting built in",
            "❌ One cluster at a time",
            "❌ Raw JSON only",
            "⚠️ Vault audit is comprehensive but not formatted for auditors",
            "⚠️ Within Vault only — no app or network context",
        ],
        "Vault + SIEM (e.g. Splunk, Datadog, Elastic)": [
            "✅ App logs + network + cloud events",
            "✅ Years of retention, indexed",
            "✅ Behavioral baselines, ML anomaly detection",
            "✅ PagerDuty, Slack, email alerts",
            "✅ All namespaces, all clusters",
            "✅ AI-powered threat summaries",
            "✅ SOC 2, PCI DSS, HIPAA report templates",
            "✅ Full kill chain across all systems",
        ],
    }
    st.dataframe(pd.DataFrame(siem_capabilities), use_container_width=True, hide_index=True)

    st.markdown("---")

    # ── The Answer ────────────────────────────────────────────────────────────
    st.subheader("🎯 The Answer for This Demo")
    st.info(
        "**For this demo:** Vault audit logs alone are fully sufficient. "
        "Every event — login, policy mapping, credential issuance, and expiry — "
        "is in the audit log, structured as JSON, and readable here without any "
        "additional tooling.\n\n"
        "**For production:** Pair Vault with a SIEM. Vault's structured JSON audit "
        "log is an ideal SIEM input — every event is already identity-correlated, "
        "timestamped, and categorized. Tools like Splunk, Datadog, and Elastic have "
        "native Vault integrations that can ingest, parse, and alert on these logs "
        "within minutes of setup."
    )

    st.markdown("---")
    st.markdown(
        "**The key insight:** Vault doesn't just log *what happened* — it logs "
        "*who did it, with what identity, under what policy, and for how long*. "
        "This is far richer than traditional access logs, and makes SIEM correlation "
        "dramatically more effective when you do add one."
    )
